apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: NAMESPACE_PLACEHOLDER
spec:
  selector:
    app: java-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
  type: NodePort
